name: check-secrets
on: pull_request
jobs:
  check-signature:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ${{ GITHUB_REPOSITORY }} 
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
        


