name: check-secrets
on: pull_request
jobs:
  check-signature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@v0.9l-beta

        


