name: encorcing-signing
on: pull_request
jobs:
  check-signature:
    runs-on: ubuntu-latest
    steps:
      - name: enforce-signing
        run: echo "Encorcing logic here"
      - name: Check Actions
        uses: giner/check-actions@1476aa8d5fb9bd940f62d5660559d521b367e219

